#!/bin/bash

# notes:
# use backslash before commonly aliased commands

set -e

case "$1" in

# Build a tagged container imaged based on a *path*
# TODO: pass options (`-rm` looks promising)
b)
    dockerfile_location=${2:-"."}
    name=$(cd $dockerfile_location && echo ${PWD##*/})
    docker build -t $name $dockerfile_location
    ;;


# Log into a container/image
bash)
    docker run -i -t ${@:2} /bin/bash
    ;;

# Delete all untagged containers
clean)
    docker rm $(docker ps -a | awk '{print $1"\t"$2'} | \grep -v ':' | cut -f1)
    ;;

# Delete all untagged images
cleani)
    docker rmi $(docker images | awk '{print $2"\t"$3}' | \grep ^\< | cut -f2)
    ;;

# List images, filtering out untagged images
images)
    docker images | \grep -v ^\<
    ;;

# Get the IP address of a running container
ip)
    docker inspect $2 | python -c 'import json,sys;obj=json.load(sys.stdin);print obj[0]["NetworkSettings"]["IPAddress"]'
    ;;

# Stop all running containers
stopall)
    docker stop $(docker ps -q)
    ;;

# Anything else you try gets passed directly to `docker`
*)
    docker $@
    ;;

esac
